src/java/co/com/vencimientospersonales/controlador/ContactoController.java
package co.com.vencimientospersonales.controlador;

import co.com.vencimientospersonales.entidades.Contacto;
import co.com.vencimientospersonales.controlador.util.JsfUtil;
import co.com.vencimientospersonales.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("contactoController")
@SessionScoped
public class ContactoController implements Serializable {

    @EJB
    private co.com.vencimientospersonales.controlador.ContactoFacade ejbFacade;
    private List<Contacto> items = null;
    private Contacto selected;

    public ContactoController() {
    }

    public Contacto getSelected() {
        return selected;
    }

    public void setSelected(Contacto selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ContactoFacade getFacade() {
        return ejbFacade;
    }

    public Contacto prepareCreate() {
        selected = new Contacto();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ContactoCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ContactoUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ContactoDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Contacto> getItems() {
       // if (items == null) {
            items = getFacade().findAll();
        //}
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Contacto getContacto(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Contacto> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Contacto> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Contacto.class)
    public static class ContactoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ContactoController controller = (ContactoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "contactoController");
            return controller.getContacto(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Contacto) {
                Contacto o = (Contacto) object;
                return getStringKey(o.getIdContacto());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Contacto.class.getName()});
                return null;
            }
        }

    }

}

web/contacto/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ContactoCreateDlg" widgetVar="ContactoCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateContactoTitle}">
            <h:form id="ContactoCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{contactoController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateContactoLabel_nombreContacto}" for="nombreContacto" />
                        <p:inputText id="nombreContacto" value="#{contactoController.selected.nombreContacto}" title="#{bundle.CreateContactoTitle_nombreContacto}" required="true" requiredMessage="#{bundle.CreateContactoRequiredMessage_nombreContacto}"/>
                        <p:outputLabel value="#{bundle.CreateContactoLabel_descripcionContacto}" for="descripcionContacto" />
                        <p:inputText id="descripcionContacto" value="#{contactoController.selected.descripcionContacto}" title="#{bundle.CreateContactoTitle_descripcionContacto}" />
                        <p:outputLabel value="#{bundle.CreateContactoLabel_telefonoContacto}" for="telefonoContacto" />
                        <p:inputText id="telefonoContacto" value="#{contactoController.selected.telefonoContacto}" title="#{bundle.CreateContactoTitle_telefonoContacto}" required="true" requiredMessage="#{bundle.CreateContactoRequiredMessage_telefonoContacto}"/>
                        <p:outputLabel value="#{bundle.CreateContactoLabel_direccionContacto}" for="direccionContacto" />
                        <p:inputText id="direccionContacto" value="#{contactoController.selected.direccionContacto}" title="#{bundle.CreateContactoTitle_direccionContacto}" required="true" requiredMessage="#{bundle.CreateContactoRequiredMessage_direccionContacto}"/>
                        <p:outputLabel value="#{bundle.CreateContactoLabel_ubicacionContacto}" for="ubicacionContacto" />
                        <p:inputText id="ubicacionContacto" value="#{contactoController.selected.ubicacionContacto}" title="#{bundle.CreateContactoTitle_ubicacionContacto}" />
                        <p:outputLabel value="#{bundle.CreateContactoLabel_codigoLocalidad}" for="codigoLocalidad" />
                        <p:selectOneMenu id="codigoLocalidad" value="#{contactoController.selected.codigoLocalidad}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_codigoLocalidad}">
                            <f:selectItems value="#{localidadController.itemsAvailableSelectOne}"
                                           var="codigoLocalidadItem"
                                           itemValue="#{codigoLocalidadItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateContactoLabel_tipoContacto}" for="tipoContacto" />
                        <p:selectOneMenu id="tipoContacto" value="#{contactoController.selected.tipoContacto}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_tipoContacto}">
                            <f:selectItems value="#{tipoContactoController.itemsAvailableSelectOne}"
                                           var="tipoContactoItem"
                                           itemValue="#{tipoContactoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{contactoController.create}" value="#{bundle.Save}" update="display,:ContactoListForm:datalist,:growl" oncomplete="handleSubmit(args,'ContactoCreateDialog');"/>
                    <p:commandButton immediate="true" value="#{bundle.Cancel}" onclick="ContactoCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/contacto/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ContactoEditDlg" widgetVar="ContactoEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditContactoTitle}">
            <h:form id="ContactoEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{contactoController.selected != null}">
                        <p:outputLabel value="#{bundle.EditContactoLabel_nombreContacto}" for="nombreContacto" />
                        <p:inputText id="nombreContacto" value="#{contactoController.selected.nombreContacto}" title="#{bundle.EditContactoTitle_nombreContacto}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_nombreContacto}"/>
                        <p:outputLabel value="#{bundle.EditContactoLabel_descripcionContacto}" for="descripcionContacto" />
                        <p:inputText id="descripcionContacto" value="#{contactoController.selected.descripcionContacto}" title="#{bundle.EditContactoTitle_descripcionContacto}" />
                        <p:outputLabel value="#{bundle.EditContactoLabel_telefonoContacto}" for="telefonoContacto" />
                        <p:inputText id="telefonoContacto" value="#{contactoController.selected.telefonoContacto}" title="#{bundle.EditContactoTitle_telefonoContacto}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_telefonoContacto}"/>
                        <p:outputLabel value="#{bundle.EditContactoLabel_direccionContacto}" for="direccionContacto" />
                        <p:inputText id="direccionContacto" value="#{contactoController.selected.direccionContacto}" title="#{bundle.EditContactoTitle_direccionContacto}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_direccionContacto}"/>
                        <p:outputLabel value="#{bundle.EditContactoLabel_ubicacionContacto}" for="ubicacionContacto" />
                        <p:inputText id="ubicacionContacto" value="#{contactoController.selected.ubicacionContacto}" title="#{bundle.EditContactoTitle_ubicacionContacto}" />
                        <p:outputLabel value="#{bundle.EditContactoLabel_codigoLocalidad}" for="codigoLocalidad" />
                        <p:selectOneMenu id="codigoLocalidad" value="#{contactoController.selected.codigoLocalidad}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_codigoLocalidad}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{localidadController.itemsAvailableSelectOne}"
                                           var="codigoLocalidadItem"
                                           itemValue="#{codigoLocalidadItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditContactoLabel_tipoContacto}" for="tipoContacto" />
                        <p:selectOneMenu id="tipoContacto" value="#{contactoController.selected.tipoContacto}" required="true" requiredMessage="#{bundle.EditContactoRequiredMessage_tipoContacto}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{tipoContactoController.itemsAvailableSelectOne}"
                                           var="tipoContactoItem"
                                           itemValue="#{tipoContactoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{contactoController.update}" value="#{bundle.Save}" update="display,:ContactoListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ContactoEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ContactoEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/contacto/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListContactoTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ContactoListForm">
                <p:panel header="#{bundle.ListContactoTitle}">
                    <p:dataTable id="datalist" value="#{contactoController.items}" var="item"
                                 selectionMode="single" selection="#{contactoController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idContacto}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_idContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.idContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_nombreContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombreContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_descripcionContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.descripcionContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_telefonoContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefonoContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_direccionContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccionContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_ubicacionContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.ubicacionContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_codigoLocalidad}"/>
                            </f:facet>
                            <h:outputText value="#{item.codigoLocalidad.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContactoTitle_tipoContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipoContacto.nombreTipoContacto}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{contactoController.prepareCreate}" update=":ContactoCreateForm" oncomplete="PF('ContactoCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ContactoViewForm" oncomplete="PF('ContactoViewDialog').show()" disabled="#{empty contactoController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ContactoEditForm" oncomplete="PF('ContactoEditDialog').show()" disabled="#{empty contactoController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{contactoController.destroy}" update=":growl,datalist" disabled="#{empty contactoController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/contacto/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ContactoViewDlg" widgetVar="ContactoViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewContactoTitle}">
            <h:form id="ContactoViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{contactoController.selected != null}">
                        <h:outputText value="#{bundle.ViewContactoLabel_idContacto}"/>
                        <h:outputText value="#{contactoController.selected.idContacto}" title="#{bundle.ViewContactoTitle_idContacto}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_nombreContacto}"/>
                        <h:outputText value="#{contactoController.selected.nombreContacto}" title="#{bundle.ViewContactoTitle_nombreContacto}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_descripcionContacto}"/>
                        <h:outputText value="#{contactoController.selected.descripcionContacto}" title="#{bundle.ViewContactoTitle_descripcionContacto}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_telefonoContacto}"/>
                        <h:outputText value="#{contactoController.selected.telefonoContacto}" title="#{bundle.ViewContactoTitle_telefonoContacto}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_direccionContacto}"/>
                        <h:outputText value="#{contactoController.selected.direccionContacto}" title="#{bundle.ViewContactoTitle_direccionContacto}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_ubicacionContacto}"/>
                        <h:outputText value="#{contactoController.selected.ubicacionContacto}" title="#{bundle.ViewContactoTitle_ubicacionContacto}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_codigoLocalidad}"/>
                        <h:outputText value="#{contactoController.selected.codigoLocalidad}" title="#{bundle.ViewContactoTitle_codigoLocalidad}"/>
                        <h:outputText value="#{bundle.ViewContactoLabel_tipoContacto}"/>
                        <h:outputText value="#{contactoController.selected.tipoContacto}" title="#{bundle.ViewContactoTitle_tipoContacto}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ContactoViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>